language: php
php:
  - '7.2'
install:
  - composer install
  - php bin/console doctrine:migrations:migrate --no-interaction
script:
  - phpunit --configuration phpunit.xml --testsuite unit
  - phpunit --configuration phpunit.xml --testsuite integration