services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true #TODO Change this after upgrade to 4.1

    # You have to maintain this list manually in order to decouple doctrine from Domain
    App\Domain\SnackMachine\SnackMachineRepository: '@App\Database\Repository\DoctrineSnackMachineRepository'
    App\Domain\SnackMachine\SnackRepository: '@App\Database\Repository\DoctrineSnackRepository'

    App\Database\:
      resource: '../src/Database/*'
      exclude: '../src/Database/Migrations'

    App\UI\:
        resource: '../src/UI'
        tags: ['controller.service_arguments']
